# Generated by Django 3.2.2 on 2021-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='tip',
            name='downvote_users',
            field=models.ManyToManyField(to='ex.Downvote'),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote_users',
            field=models.ManyToManyField(to='ex.Upvote'),
        ),
    ]
